baseURL: "https://yoandresaav.github.io/blog/"
languageCode: en-us
title: Yoandre
theme: "PaperMod"

params:
    defaultTheme: auto
    env: production

    profileMode:
        enabled: true
        title: "Yoandre Saavedra Gonzalez"
        subtitle: "Full Stack Developer"
        imageUrl: "https://pbs.twimg.com/profile_images/1184215678208937985/botpc0h-_400x400.jpg"
        imageTitle: "Yoandre Twitter Photo"
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: Posts
              url: "/blog/post"
            - name: Github
              url: "https://github.com"

    socialIcons:
        - name: "Facebook"
          url: "<link>"
        - name: "Twitter"
          url: "<link>"

    ShowShareButtons: true
    ShowReadingTime: true

    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
