baseURL: "https://yoandresaav.github.io/blog/"
languageCode: en-us
title: Yoandre Saav
theme: "PaperMod"
googleAnalytics: G-ZB70WN60R4

params:
    defaultTheme: auto
    env: production

    profileMode:
        enabled: true
        title: "Yoandre Saavedra González"
        subtitle: "Full Stack Developer"
        imageUrl: profile-yoa.png
        # imageUrl: "https://freepngimg.com/download/youtube/63841-profile-twitch-youtube-avatar-discord-free-download-image.png"
        imageTitle: "Yoandre Profile"
        imageWidth: 160
        imageHeight: 160
        buttons:
            - name: Posts
              url: "/blog/posts"
            - name: Who I Am
              url: "/blog/whoiam"
            - name: Github
              url: "https://github.com/yoandresaav/"

    socialIcons:
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/yoandre-saavedra/"
        - name: "Twitter"
          url: "https://twitter.com/yoandresaav"

    ShowShareButtons: true
    ShowReadingTime: true

    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true

    ShowToc: false
    ShowCodeCopyButtons: true

